import { z } from 'zod';

export interface CanonicalEvent {
  client_id: string;
  metric: string;
  amount: number;
  timestamp: string; // ISO-8601 string
  is_timestamp_fallback?: boolean; // True if timestamp was generated by server fallback
  extra_fields?: Record<string, any>;
}

export const CanonicalEventSchema = z.object({
  client_id: z.string({ required_error: 'client_id (or source) is required' }).min(1, 'client_id cannot be empty'),
  metric: z.string({ required_error: 'metric is required' }).min(1, 'metric cannot be empty'),
  amount: z.number({ required_error: 'amount must be a valid number' }).refine(val => !isNaN(val), 'amount must be a valid number'),
  timestamp: z.string().datetime({ message: 'timestamp must be a valid ISO-8601 string' }),
  is_timestamp_fallback: z.boolean().optional().default(false),
  extra_fields: z.record(z.unknown()).optional().default({})
});

export type RawEventStatus = 'RECEIVED' | 'PROCESSED' | 'REJECTED' | 'DUPLICATE' | 'FAILED';

export interface IngestResponse {
  success: boolean;
  status: RawEventStatus;
  raw_event_id: number;
  fingerprint?: string;
  normalized_event?: CanonicalEvent;
  message?: string;
  error?: string;
}
